---
- name: "Pull Master Branch of wipadventure"
  git:
    repo: "https://github.com/diegodelrieu/WipAdventure"
    dest: "/opt/wipadventure"

- name: "Create wipadventure dir"
  file:
    path: "/opt/wipadventure"
    state: "directory"
    group: "docker"
    recurse: true
    mode: "0775"

- name: "supply .env file"
  template:
    src: "env.j2"
    dest: "/opt/wipadventure/contrib/docker/.env"
    group: "operator"
    mode: "0770"

- name: "supply docker-compose file"
  template:
    src: "docker-compose.yml.j2"
    dest: "/opt/wipadventure/contrib/docker/docker-compose.yml"
    group: "operator"
    mode: "0770"

- name: "Create wipadventure dir"
  file:
    path: "/opt/wipadventure/contrib/docker/letsencrypt"
    state: "directory"
    group: "docker"
    recurse: true
    mode: "0775"


- name: "Conclusion"
  debug:
    msg: "wipadventure is prepared. Have a look in /opt/wipadventure"
